# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

start = Time.now

sequence = [1, 2]
while (sequence[-1] < 4000000)
  new = sequence[-1] + sequence[-2]
  sequence << new
end

sequence.delete_if { |x| x > 4000000 }

sum = 0
sequence.each { |x| sum = sum + x if (x % 2 == 0) }

puts sum
puts (Time.now - start)
